export enum AppRoutes {
  Home = "/",
  Profile = "/profile",
  Login = "/auth/login",
  Register = "/auth/registration",
  Cars = "/cars",
  Engine = "/engine",
  Admin = "/admin",
  CreateCar = "/cars/create",
  CreateEngine = "/engine/create",
  Details = "/details",
  CreateDetail = "/details/create",
}

export enum Theme {
  Light = "light",
  Dark = "dark",
}

export const NavigationList = [
  { name: "Home", ref: AppRoutes.Home },
  { name: "Cars", ref: AppRoutes.Cars },
  // { name: "Engines", ref: AppRoutes.CreateEngine },
  { name: "Payment", ref: AppRoutes.Details },
  { name: "Profile", ref: AppRoutes.Profile },
];

export const EngineFuel = {
  Petrol: "Petrol",
  Diesel: "Diesel",
  Propane: "Propane",
  Electric: "Electric",
  Hybrid: "Hybrid",
};

export const CarsBrand = [
  { value: "", label: "All" },
  { value: "Acura", label: "Acura" },
  { value: "Alfa Romeo", label: "Alfa Romeo" },
  { value: "Audi", label: "Audi" },
  { value: "BMW", label: "BMW" },
  { value: "Buick", label: "Buick" },
  { value: "Cadillac", label: "Cadillac" },
  { value: "Chevrolet", label: "Chevrolet" },
  { value: "Chrysler", label: "Chrysler" },
  { value: "Citroen", label: "Citroen" },
  { value: "Dodge", label: "Dodge" },
  { value: "Ferrari", label: "Ferrari" },
  { value: "Fiat", label: "Fiat" },
  { value: "Ford", label: "Ford" },
  { value: "Genesis", label: "Genesis" },
  { value: "GMC", label: "GMC" },
  { value: "Honda", label: "Honda" },
  { value: "Hyundai", label: "Hyundai" },
  { value: "Infiniti", label: "Infiniti" },
  { value: "Jaguar", label: "Jaguar" },
  { value: "Jeep", label: "Jeep" },
  { value: "Kia", label: "Kia" },
  { value: "Land Rover", label: "Land Rover" },
  { value: "Lexus", label: "Lexus" },
  { value: "Lincoln", label: "Lincoln" },
  { value: "Maserati", label: "Maserati" },
  { value: "Mazda", label: "Mazda" },
  { value: "Mercedes-Benz", label: "Mercedes-Benz" },
  { value: "Mini", label: "Mini" },
  { value: "Mitsubishi", label: "Mitsubishi" },
  { value: "Nissan", label: "Nissan" },
  { value: "Pagani", label: "Pagani" },
  { value: "Peugeot", label: "Peugeot" },
  { value: "Porsche", label: "Porsche" },
  { value: "Ram", label: "Ram" },
  { value: "Renault", label: "Renault" },
  { value: "Saab", label: "Saab" },
  { value: "Subaru", label: "Subaru" },
  { value: "Suzuki", label: "Suzuki" },
  { value: "Tesla", label: "Tesla" },
  { value: "Toyota", label: "Toyota" },
  { value: "Volkswagen", label: "Volkswagen" },
  { value: "Volvo", label: "Volvo" },
];
